### PR TITLE
feature: add support for aton virtual flag

### PR DESCRIPTION
**Pull request by sbender9**
See #166

### CODE REVIEW

**Comment by sbender9** [comment]
https://github.com/SignalK/specification/issues/563

**Comment by tkurki** [comment]
Rebased on master, but some tests fail.

**Comment by sbender9** [comment]
It says all checks passed??

**Comment by tkurki** [comment]
Still fails locally for me.

**Comment by tkurki** [comment]
Just a local glitch.

**Comment by Hakansv** [comment]
@sbender9  @tkurki 
I think the logic for the virtual flag has got the opposite value.
This one is Real.
Håkan
image

**Comment by sbender9** [comment]
Do you have the sentence for that one?

**Comment by Hakansv** [comment]
Here is one of each
https://github.com/SignalK/signalk-parser-nmea0183/issues/166#issuecomment-592054206

**Comment by Hakansv** [comment]
@sbender9 
Here goes dragons...
For the two examples in the file above the virtual flags seems correct. (They are from Belgium)
My comment was about two Swedish AtoN that has got opposite flag from what have been observed before.
My earlier indication is taken from the mmsi number saying a "6" in position like: xxzzz6xxx but the own indication from the VDM message would be more reliable.
A further investigation has shown you data is correct. The SE authorities has probably misused the mmsi number. 
And when I compare to the use of VDM data in OCPN where we have the same message parsing as you have used all is correct.
Please close this comment. Sorry for the trouble.
Thanks
Håkan

**Pull request merged**
