### PR TITLE
Add HDT and HDM Codecs

### PR DESCRIPTION
**Pull request by bobmor99**

### CODE REVIEW

**Comment by tkurki** [comment]
Great! Would adding some tests be too much to ask?


Something like https://github.com/SignalK/n2k-signalk/blob/master/test/127250_heading.js

**Comment by bobmor99** [comment]
I tested end-to-end by creating each message type in my arduino and
observing the expected result in your instrumentpanel app. (And checked
wscat output along the way.)
If "chai testing" is standard procedure, I will learn chai and report back.

**Comment by tkurki** [comment]
The idea of runnable tests, especially in an open source project, is that the next person touching the code can run the tests to make sure everything is still working.

So please if you can spare the effor please add tests.

**Comment by bobmor99** [comment]
Will do. 
Could you provide a simple overview of chai testing for SK changes?
I looked at your link but don't understand how to utilize it.
Is it part of github?  I will google but was wondering if there anything that is SK-specific.
Thanks for all your help.

**Comment by tkurki** [comment]
I'l try to find the time to create a base test over the weekend.

**Comment by tkurki** [comment]
You can actually extend the existing parsing test: https://github.com/SignalK/signalk-parser-nmea0183/blob/master/test/parsing.js.

I also created a failing test to demonstrate a bug here: https://github.com/SignalK/signalk-parser-nmea0183/commit/2e2bcd5b336de85a1e9bb3a2c17d10afab85fa89
I like this testing style personally a lot better, as it is more specific (one sentence, one test file) and the error messages can be more specific as the assertions are not "match-all".

**Comment by bobmor99** [comment]
I'd like to verify that I am on the right path.

Some sample $GPHDM messages originating from my arduino:
~/signalk-server-node/node_modules/nmea0183-signalk/test/logs$ cat
gphdm.msgs
$GPHDM,319.5,T*22
$GPHDM,306.0,T*29
$GPHDM,291.3,T*25

-----------------
Modified clone of
~/signalk-server-node/node_modules/nmea0183-signalk/test/logs/runaislog.js
to reference ./gphdm.msgs.
~/signalk-server-node/node_modules/nmea0183-signalk/test/logs$ grep
gphdm.msgs gphdm.js
fs.createReadStream(path.join(__dirname, './gphdm.msgs'), { encoding:
'utf8' }).pipe(parser);

-------------------
Added the following stanza to
~/signalk-server-node/node_modules/nmea0183-signalk/test/parsing.js:
describe('HDM parser; sentence with course magnetic data', function() {
  verifyParsing('$GPHDM,296.4,T*25',
                {
                  "vessels": {
                    "77665544": {
                      "navigation": {
                        "headingMagnetic": {
                          "value": 123.4,
                          "source": {
                            "label": "signalk-parser-nmea0183",
                            "type": "NMEA0183",
                            "src": "HDM"
                          }
                        }
                      },
                      "mmsi": "77665544"
                    }
                  },
                  "version": 1,
                  "self": "77665544"
                });
});

--------------------------------------------------------
Ran ~/signalk-server-node/node_modules/nmea0183-signalk/test/logs/gphdm.js
and observed:
~/signalk-server-node/node_modules/nmea0183-signalk/test/logs$ node
./gphdm.js
{
  "self": "CABC8FF9",
  "version": 1,
  "vessels": {
    "CABC8FF9": {
      "uuid": "CABC8FF9",
      "navigation": {
        "headingMagnetic": {
          "timestamp": "2015-04-01T17:21:33.000Z",
          "source": {
            "type": "NMEA0183",
            "src": "HDM",
            "label": "signalk-parser-nmea0183"
          },
          "value": 319.5
        }
      }
    }
  }
}



{
  "self": "CABC8FF9",
  "version": 1,
  "vessels": {
    "CABC8FF9": {
      "uuid": "CABC8FF9",
      "navigation": {
        "headingMagnetic": {
          "timestamp": "2015-04-01T17:21:33.000Z",
          "source": {
            "type": "NMEA0183",
            "src": "HDM",
            "label": "signalk-parser-nmea0183"
          },
          "value": 306
        }
      }
    }
  }
}



{
  "self": "CABC8FF9",
  "version": 1,
  "vessels": {
    "CABC8FF9": {
      "uuid": "CABC8FF9",
      "navigation": {
        "headingMagnetic": {
          "timestamp": "2015-04-01T17:21:33.000Z",
          "source": {
            "type": "NMEA0183",
            "src": "HDM",
            "label": "signalk-parser-nmea0183"
          },
          "value": 291.3
        }
      }
    }
  }
}

-----------------------------------------------------
What's next?
Do I need to do a github pull request to get my HDM parser stanza included
in signalk-server-node/node_modules/nmea0183-signalk/test/parsing.js?  Same
for my sample message file(s).
It wouldn't surprise me if I'm completely missing the boat here.

**Comment by tkurki** [comment]
You can run the tests under test/ (there's just one actually, parsing.js) with `npm test`in the root of your copy of nmea0183-signalk.

Instead of explaining in writing your changes you can just commit to the branch this PR is based on. This way your changes are a lot easier for me to understand, as Github does a neat job of providing different views about the changes you've introduced.

Just add & commit the new files & changes to the same branch as your HDT and HDM.js and push to your github repo. This PR still references that branch in your repo and anything you add will be part of the PR.

**Comment by tkurki** [comment]
So the real test is parsing.js, stuff under logs is just extra baggage, you don't need to modify any of that.

**Comment by tkurki** [comment]
@bobmor99 should I merge or are there tests waiting just around the corner?

**Comment by bobmor99** [comment]
Go ahead and merge. I never really figured out the testing. Sorry.

**Pull request merged**
