### PR TITLE
add $ recognition

### PR DESCRIPTION
**Pull request by Thomas-GeDaD**
add $ recognition, delete signs before $ if $ available and not at the beginning of the sentence
checked with nasa Clipper instruments

### CODE REVIEW

**Comment by Thomas-GeDaD** [comment]
Hi, have edit the recognition as described. Have tested with Nasa Clipper NMEA0183 Instruments and several further NMEA0183 devices.

**Comment by joabakk** [comment]
What is the purpose of this change, and what does it solve? Please explain

**Comment by Thomas-GeDaD** [comment]
some NMEA devices like Nasa Clipper sends a 00 character before the $ sign at the beginning. SignalK can not parse this correctly. 
See this issue:
https://github.com/SignalK/signalk-server-node/issues/970

**Comment by tkurki** [comment]
I have another, more generic solution planned for this. Stay tuned.

**Comment by tkurki** [comment]
I would rather not add an extra conditional for every single user of this library just because some equipment misbehaves.

I added a PR for an option to explicitly remove NULL characters at https://github.com/SignalK/signalk-server-node/pull/1032. This will cause no overhead if the option is not turned on.

**Comment by Thomas-GeDaD** [comment]
solved with 👍 
https://github.com/SignalK/signalk-server-node/pull/1032
Hi tkurki, thanks for your support. What speaks against it to enable this option permanently in the code? I be afraid of that users irritated through this option?

**Comment by tkurki** [comment]
Just what I had said above:

>I would rather not add an extra conditional for every single user 

I would guess 99.9% of devices don't produce nulls.

The server's processing pipeline consists of several steps, sort of like unix command line pipes consist of several components. I would rather clean up input before it gets to the parser.

**Pull request closed without merging**
