### PR TITLE
update: add more ais fields and handle atons

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by sbender9** [comment]
@fabdrol is there a problem with this? I will go ahead and merge it if I don't there from you.

**Comment by fabdrol** [comment]
@sbender9 looks good, did you update/add a test?

**Comment by afischerdev** [comment]
I had also a test with the new-nmea0183-parser branch. Looks good for me as well.
Any way I have two thought on it:

- could you please add destination and callsign to the static data
- the 'atonType' comes as string. As a client developer I would like to see it as integer. Same as aisShipType or similar. E.g. if I would like to show different icons on fixed, cardinal or floating AtoNs  I have to redesign text to integer.

**Comment by tkurki** [comment]
Schema is the master for type information. (On my phone, please check yourself)

**Comment by joabakk** [comment]
```
"aisShipType": {
      "type": "number",
```

**Comment by sbender9** [comment]
@fabdrol I updated the test

**Comment by sbender9** [comment]
@afischerdev I added callsign and destination. aisShipType is a number per the current specification

**Comment by sbender9** [comment]
oops. need to fix atonType to match the spec:

```
    "atonType": {
       "enum": [
         "0 Default, Type of AtoN not specified",
         "1 Reference point",
         "2 RACON",
         "3 Fixed structures off-shore, such as oil platforms, wind farms.",
         "4 Emergency Wreck Marking Buoy",
         "5 Light, without sectors",
         "6 Light, with sectors",
         "7 Leading Light Front",
         "8 Leading Light Rear",
         "9 Beacon, Cardinal N",
         "10 Beacon, Cardinal E",
         "11 Beacon, Cardinal S",
         "12 Beacon, Cardinal W",
         "13 Beacon, Port hand",
         "14 Beacon, Starboard hand",
         "15 Beacon, Preferred Channel port hand",
         "16 Beacon, Preferred Channel starboard hand",
         "17 Beacon, Isolated danger",
         "18 Beacon, Safe water",
         "19 Beacon, Special mark",
         "20 Cardinal Mark N",
         "21 Cardinal Mark E",
         "22 Cardinal Mark S",
         "23 Cardinal Mark W",
         "24 Port hand Mark",
         "25 Starboard hand Mark",
         "26 Preferred Channel Port hand",
         "27 Preferred Channel Starboard hand",
         "28 Isolated danger",
         "29 Safe Water",
         "30 Special Mark",
         "31 Light Vessel/LANBY/Rigs"
       ]
    },```

**Comment by afischerdev** [comment]
@sbender9 great, thanks for the update, sorry, I missed registrations.imo in the morning

I was thinking only about the 'atonType' definition.
Others like aisShipType come as an integer (number enum). 
See discussion [#337](https://github.com/SignalK/specification/pull/337#issuecomment-287536205)

**Comment by sbender9** [comment]
@afischerdev I'm proposing a change to the spec on this: https://github.com/SignalK/specification/pull/384

@fabdrol you can hold of on this until that is resolved.

**Comment by afischerdev** [comment]
@sbender9 super, thanks for changing the spec 

And I'm sorry, seems I was a little confused - destination and callsign are not the only values to become a complete static data.
I forgot **registrations.imo** and **navigation.destination.eta**

Mothership and vendor values are also parts in the static data (sentence 24, part B). But this was never discussed and only mothership is delievered by the decoder.

**Comment by sbender9** [comment]
@fabdrol you can merge this now

**Comment by fabdrol** [comment]
@sbender9 the tests fail, ideas?

**Comment by sbender9** [comment]
Shoot. I forgot I'm using new code from the schema that isn't published.

**Comment by sbender9** [comment]
@tkurki can you publish the latest schema?

**Comment by tkurki** [comment]
done

**Comment by sbender9** [comment]
@fabdrol looks good now

**Comment by fabdrol** [comment]
@sbender9 merged, I'm sorry for the delay! Busy days at work...

**Pull request merged**
