### PR TITLE
seconds are missing

### PR DESCRIPTION
**Pull request by e-sailing**
The timestamp function in nmea0183-utilities has the issue

### CODE REVIEW

**Comment by sbender9** [comment]
Now the test is failing because of this change

**Comment by sbender9** [comment]
Can you update the nmea0183-utilities version to 0.6.0? Then the test should pass and I can merge

**Comment by sbender9** [comment]
Sorry, I'm asking you to update the PR. Please update the utilities version and the tests, We won't merge a pull requests with the tests failing.

**Comment by e-sailing** [comment]
I tried to fix it  with another pull request #119 (0.5.0 to 0.6.0) . But it has the same problem the other way round. The result is now with the 12 seconds but this part  with the 12 seconds isn't merged and gives an error. Please help.

**Comment by sbender9** [comment]
Put the version change in this pull request.

**Pull request merged**
