### PR TITLE
feature: identify proprietary sentences with full name

### PR DESCRIPTION
**Pull request by joabakk**
Re-opening #116 after recent changes to repo.

### CODE REVIEW

**Comment by tkurki** [comment]
Schema specifies sentences property name as three letters, you have `PNKEP`.

https://github.com/SignalK/specification/blob/master/schemas/groups/sources.json#L37

**Comment by joabakk** [comment]
Thanks @tkurki it should be ok now

**Comment by joabakk** [comment]
Can we merge this?

**Comment by joabakk** [comment]
Squashed into a single commit and force pushed. Third time lucky...

**Comment by tkurki** [comment]
Are the changes in VWR related?

Prefer let/const over var, please change.

**Comment by joabakk** [comment]
The VWR tesst used PIVWR, which in NMEA0183 book identifies it as a proprietary sentence, that's why it had to be changed. Changed to const in lib/index

**Pull request merged**
