### PR TITLE
style: Enable Eslint

### PR DESCRIPTION
**Pull request by webmasterkai**
I've started on some aslant with fixes. Maybe someone should let me know if I'm headed in the right direction with this.

### CODE REVIEW

**Comment by tkurki** [comment]
No.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
https://stackoverflow.com/questions/31605391/how-does-the-chai-expect-function-work

**Comment by webmasterkai** [comment]
I like that solution. Nice find.

Should I continue on fixing the errors?

**Comment by tkurki** [comment]
Some tests are failing, any idea why?

Sure, go ahead with the fixin’.

**Comment by tkurki** [comment]
And how do you hook eslint so that CI tests conformance?

**Comment by tkurki** [comment]
Any plans to push this forward? This touches gazillion files and will get out of date with #125.

**Comment by webmasterkai** [comment]
This is too large a project for me to enable and fix all errors. It's just more time than I have at the moment.

How do you feel about establishing some rules and then implementing them in smaller chunks and with every new commit?

**Comment by tkurki** [comment]
Adding just 1 rule and setting up eslint in general so that contributors can easily use it would be valuable.

**Pull request closed without merging**
