### PR TITLE
fix: HDG with just heading

### PR DESCRIPTION
**Pull request by tkurki**
The new parser is not working with HDG with just the heading field, which my equipment happens to produce.

### CODE REVIEW

**Comment by joabakk** [comment]
That one seems to come from d53aefe09f87cc45093ac240bb4268af5fc87819. Looks like it should have been ands and not ors? We introduced tests for empty sentences, and this one is wrongly reported as such.

**Comment by tkurki** [comment]
It is not just the check, you need to alter the way the values array is constructed.

**Comment by joabakk** [comment]
I see a few issues:
APB is incomplete
DBT empty sentence test logic (DSC type?)
GGA should accept more than 3 empty fields?
GLL, does it choke on first empty field?
HDG as mentioned
MTW, RMC, RPM, VDR, VHW missing empty test logic
VWR should accept more than 3 empty fields?

So quite a list, but still it should have been discovered before

**Comment by fabdrol** [comment]
Hmm good find, I didn’t realise that was considered a valid case (the test for choking on empty sentences verifies that the thing returns no data in that case). 

@tkurki: could you send me those sentences? I’ll change the parser’s behaviour

**Comment by tkurki** [comment]
What sentences? Did you check the code in this PR?

**Comment by fabdrol** [comment]
Not yet, I was on a mobile device. But I'll go through it for every hook. A question I'd like to ask is: is there one generic way to assess the invalidity of a incoming sentence, apart from (1) it being empty and (2) an invalid checksum? I'm proposing to add the field check to the parser before a hook is invoked (i.e. to check if it's empty) and defer any other validity check to the hooks. The hook can then take care of checking VOID flags in certain sentences, validating fields in others..

**Comment by tkurki** [comment]
Why are you adding more validation - I have not heard of any problems related to this with the old parser, is there something to fix?

**Comment by fabdrol** [comment]
I'm not saying I'm adding more validation, I was saying I'd move validating that a sentence is not empty out of the hooks and _asking_ if there're any more validations we need to do.

**Comment by tkurki** [comment]
What do you mean by _a sentence is not empty_? That it is not an empty string? Or that all fields are empty? If it is an empty string it won't be converted anyway.

My point is that for example HDG the hook can convert the data that is there and not worry about any other validation. 

In some cases there needs to be data in several fields, like variation and deviation need both the magnitude and direction. In a sense that is validation: _only output variation if both magnitude and direction fields have valid values_.

This is what it did previously: https://github.com/SignalK/signalk-parser-nmea0183/blob/v0.6.0/codecs/HDG.js#L50-L56. The conversion could be a but more strict, it only checks for `E` and `something else, but truthy`.

**Comment by tkurki** [comment]
I would really love to have a way to log everything that is **not converted** for testing and debugging, now during this upgrade and later in prod use when you get questions about _why is such and such not being shown_.

**Comment by joabakk** [comment]
I added a second debug variable and called that if the sentence was not converted. It only returned empty sentences and those without hooks for the plaka file, as could be expected. But we should not limit ourselves to the few n0183 logfiles in the server install.

**Comment by joabakk** [comment]
Good idea to check if all fields are empty before sending it to the hook @fabdrol. Makes it cleaner and easier to add new hooks. Then there are more exotic variants like HDT sending "here is the heading, but it's not valid" that need to rest in the hook. Then we could add a `nmea0183-parser-skipped` or similar debug message with the dropped sentences for the user to troubleshoot

**Pull request merged**
