### PR TITLE
add navigation.datetime

### PR DESCRIPTION
**Pull request by e-sailing**
navigation.datetime does work on NMEA2000 (pgn 126992) but not on NMEA0183
RMC has the complete date and time. Why keep differences between Signal K keys from 2000 to 0183?

### CODE REVIEW

**Comment by tkurki** [comment]
Could you please add a test for RMC, preferably with a sample from real world. See other tests in the test directory for examples.

**Comment by e-sailing** [comment]
How do I start an example from test directory?

**Comment by tkurki** [comment]
npm test

runs all the tests.

**Comment by tkurki** [comment]
Merged manually, since I fixed the commit messages (N2K parser's features are not really relevant, just the fact that navigation.datetime is added) and improved the test messages a bit.

Thank you!

**Pull request closed without merging**
