### PR TITLE
Tried to add ROT and RPM

### PR DESCRIPTION
**Pull request by joabakk**
I have added ROT and RPM to my test fork, added these to codecs/index.js and used DBT as example. It seems the parser.on('delta', function(delta) { -function is not working properly and I get timeouts in mocha. Have I forgotten something?

### CODE REVIEW

**Comment by tkurki** [comment]
Your checksums are incorrect and the parser silently ignores the input. Please fix them and everything should start working.

@fabdrol I don't think it should ignore input without any error message.

**Comment by tkurki** [comment]
You can commit the fix to your repo and I can merge this manually - I changed README on January 27th apparently after your fork and replaced the sentence list with a link to the list in code.

**Comment by joabakk** [comment]
Ok, that was embarrassing. Fixed in my repo now.

**Comment by tkurki** [comment]
Merged with #45. I squashed your commits, so nothing left for posterity to wonder about.

Schema has engine instance in the path, so I decided to just hard code one here. That might be a configurable option for Parser in the future (ping @fabdrol ).

For next time: I'd appreciate meaningful commit messages. I guess the ones you used were generated by a tool? Github and git tells what file changes were done, commit message is for a human to understand what actually changed and why. See http://chris.beams.io/posts/git-commit/.

**Pull request closed without merging**
